sudo: required

language: c++

services:
  - docker

compiler:
  - g++

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

branches:
 only:
  - master

before_install:
 - docker pull mingchen/tc-client
 - docker run -d mingchen/tc-client /bin/sh -c "git clone https://github.com/sbu-fsl/tc-server.git; ./tc-server/src/scripts/build-and-run.sh;"

script: mkdir txn-compound/tc_client/build && cd txn-compound/tc_client/build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make && make install && ./MainNFSD/tc_test_write

notifications:
  email:
    recepients:
      - v.mingchen@gmail.com

    on_success: always
    on_failure: always
