sudo: required

language: c++

services:
  - docker

compiler:
  - g++

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

branches:
 only:
  - master

before_install:
 - docker pull mingchen/tc-client
 # Because docker drop CAP_DAC_READ_SEARCH, so name_to_handle_at() will fail.
 # Therefore, we cannot run the Ganesha server in Docker!
 # - docker run -d mingchen/tc-client /bin/sh -c "git clone https://github.com/sbu-fsl/tc-server.git; ./tc-server/src/scripts/build-and-run.sh;"

script: docker run mingchen/tc-client /bin/sh -c "git clone https://github.com/sbu-fsl/txn-compound.git /tc-latest && /tc-latest/scripts/build-and-test.sh"

#script: docker run mingchen/tc-client /bin/sh -c "git clone https://github.com/sbu-fsl/tc-server.git && ./tc-server/src/scripts/build-and-run.sh && git clone https://github.com/sbu-fsl/txn-compound.git /tc-latest && /tc-latest/scripts/build-and-test.sh"

notifications:
  email:
    recepients:
      - v.mingchen@gmail.com

    on_success: always
    on_failure: always
